### ISSUE TITLE
Need to update code....

### ISSUE THREAD

**Issue by alkopit** [drowolath/flask-ldap-auth#2]

**Comment by gelie** [comment]
I modified the function "def verify_password(self, password)" to allow **authenticated searches** of an Active Directory LDAP server (flask_ldap_auth.py), within a **SUBTREE**, with the "**sAMAccountName**".

It is crude, but I just needed to get it to work at the time!!

[flask_ldap_auth.py.zip](https://github.com/drowolath/flask-ldap-auth/files/3372838/flask_ldap_auth.py.zip)

**Comment by drowolath** [comment]
Hello @gelie , sorry for the late reply but I was afk for a while.
Could you submit a PR so I can review and eventually merge your proposition ? It may be of interest to other people ;)

**Comment by drowolath** [comment]
Hello @gelie,
I just pushed to master branch a small patch that allows custom calls to the /request-token endpoint.
Let me know if it works for you or if it can be improved
