### ISSUE TITLE
Error during install api.

### ISSUE THREAD

**Issue by raucci2000** [drowolath/flask-ldap-auth#3]
Hi folks!

I'm using Python 3.6.4 (x64). When I try to install this api by command line "pip install flask-ldap-auth", appears the following message error:

**Comment by drowolath** [comment]
Hello @raucci2000 ,

could you please paste the entire error message you're getting?

I did try to install under python3.6 and I'm getting no error at all.

**Comment by raucci2000** [comment]
Hello Thomas, sure! Acoording your request follow entire error message:

Building wheels for collected packages: python-ldap
  Building wheel for python-ldap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\projetos\python\scraping\env_erick36\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ANDRE~1.RAU\\AppData\\Local\\Temp\\pip-install-88240aor\\python-ldap\\setup.py'"'"'; __file__='"'"'C:\\Users\\ANDRE~1.RAU\\AppData\\Local\\Temp\\pip-install-88240aor\\python-ldap\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ANDRE~1.RAU\AppData\Local\Temp\pip-wheel-tvkrelrg' --python-tag cp36
       cwd: C:\Users\ANDRE~1.RAU\AppData\Local\Temp\pip-install-88240aor\python-ldap\
  Complete output (78 lines):
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-3.6
  copying Lib\ldapurl.py -> build\lib.win-amd64-3.6
  copying Lib\ldif.py -> build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\async.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\asyncsearch.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\cidict.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\compat.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\constants.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\dn.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\filter.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\functions.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\ldapobject.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\logger.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\modlist.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\pkginfo.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\resiter.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\sasl.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\syncrepl.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\__init__.py -> build\lib.win-amd64-3.6\ldap
  creating build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\deref.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\libldap.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\openldap.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\pagedresults.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\ppolicy.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\psearch.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\pwdpolicy.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\readentry.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\sessiontrack.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\simple.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\sss.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\vlv.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\__init__.py -> build\lib.win-amd64-3.6\ldap\controls
  creating build\lib.win-amd64-3.6\ldap\extop
  copying Lib\ldap\extop\dds.py -> build\lib.win-amd64-3.6\ldap\extop
  copying Lib\ldap\extop\__init__.py -> build\lib.win-amd64-3.6\ldap\extop
  creating build\lib.win-amd64-3.6\ldap\schema
  copying Lib\ldap\schema\models.py -> build\lib.win-amd64-3.6\ldap\schema
  copying Lib\ldap\schema\subentry.py -> build\lib.win-amd64-3.6\ldap\schema
  copying Lib\ldap\schema\tokenizer.py -> build\lib.win-amd64-3.6\ldap\schema
  copying Lib\ldap\schema\__init__.py -> build\lib.win-amd64-3.6\ldap\schema
  creating build\lib.win-amd64-3.6\slapdtest
  copying Lib\slapdtest\_slapdtest.py -> build\lib.win-amd64-3.6\slapdtest
  copying Lib\slapdtest\__init__.py -> build\lib.win-amd64-3.6\slapdtest
  running egg_info
  writing Lib\python_ldap.egg-info\PKG-INFO
  writing dependency_links to Lib\python_ldap.egg-info\dependency_links.txt
  writing requirements to Lib\python_ldap.egg-info\requires.txt
  writing top-level names to Lib\python_ldap.egg-info\top_level.txt
  reading manifest file 'Lib\python_ldap.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'Doc\.build'
  writing manifest file 'Lib\python_ldap.egg-info\SOURCES.txt'
  creating build\lib.win-amd64-3.6\slapdtest\certs
  copying Lib\slapdtest\certs\README -> build\lib.win-amd64-3.6\slapdtest\certs
  copying Lib\slapdtest\certs\ca.conf -> build\lib.win-amd64-3.6\slapdtest\certs
  copying Lib\slapdtest\certs\ca.pem -> build\lib.win-amd64-3.6\slapdtest\certs
  copying Lib\slapdtest\certs\client.conf -> build\lib.win-amd64-3.6\slapdtest\certs
  copying Lib\slapdtest\certs\client.key -> build\lib.win-amd64-3.6\slapdtest\certs
  copying Lib\slapdtest\certs\client.pem -> build\lib.win-amd64-3.6\slapdtest\certs
  copying Lib\slapdtest\certs\gencerts.sh -> build\lib.win-amd64-3.6\slapdtest\certs
  copying Lib\slapdtest\certs\gennssdb.sh -> build\lib.win-amd64-3.6\slapdtest\certs
  copying Lib\slapdtest\certs\server.conf -> build\lib.win-amd64-3.6\slapdtest\certs
  copying Lib\slapdtest\certs\server.key -> build\lib.win-amd64-3.6\slapdtest\certs
  copying Lib\slapdtest\certs\server.pem -> build\lib.win-amd64-3.6\slapdtest\certs
  running build_ext
  building '_ldap' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\Modules
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.2.0 "-DLDAPMODULE_AUTHOR=python-ldap project" "-DLDAPMODULE_LICENSE=Python style" -IModules -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -IC:\Sybase\OCS-15_0\include -IC:\bvsistemas\servers\IBM\MQ\tools\c\include -IC:\bvsistemas\servers\IBM\MQ\tools\cplus\include /TcModules/LDAPObject.c /Fobuild\temp.win-amd64-3.6\Release\Modules/LDAPObject.obj
  LDAPObject.c
  c:\users\andre.raucci\appdata\local\temp\pip-install-88240aor\python-ldap\modules\constants.h(7): fatal error C1083: Cannot open include file: 'lber.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for python-ldap
  Running setup.py clean for python-ldap
Failed to build python-ldap
Installing collected packages: Werkzeug, itsdangerous, MarkupSafe, Jinja2, click, Flask, pyasn1, pyasn1-modules, python-ldap, pyldap, flask-ldap-auth
  Running setup.py install for python-ldap ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\projetos\python\scraping\env_erick36\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ANDRE~1.RAU\\AppData\\Local\\Temp\\pip-install-88240aor\\python-ldap\\setup.py'"'"'; __file__='"'"'C:\\Users\\ANDRE~1.RAU\\AppData\\Local\\Temp\\pip-install-88240aor\\python-ldap\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ANDRE~1.RAU\AppData\Local\Temp\pip-record-zkakm9rc\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\projetos\python\scraping\env_erick36\include\site\python3.6\python-ldap'
         cwd: C:\Users\ANDRE~1.RAU\AppData\Local\Temp\pip-install-88240aor\python-ldap\
    Complete output (78 lines):
    running install
    running build
    running build_py
    creating build\lib.win-amd64-3.6
    copying Lib\ldapurl.py -> build\lib.win-amd64-3.6
    copying Lib\ldif.py -> build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\async.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\asyncsearch.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\cidict.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\compat.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\constants.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\dn.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\filter.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\functions.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\ldapobject.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\logger.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\modlist.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\pkginfo.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\resiter.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\sasl.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\syncrepl.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\__init__.py -> build\lib.win-amd64-3.6\ldap
    creating build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\deref.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\libldap.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\openldap.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\pagedresults.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\ppolicy.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\psearch.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\pwdpolicy.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\readentry.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\sessiontrack.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\simple.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\sss.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\vlv.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\__init__.py -> build\lib.win-amd64-3.6\ldap\controls
    creating build\lib.win-amd64-3.6\ldap\extop
    copying Lib\ldap\extop\dds.py -> build\lib.win-amd64-3.6\ldap\extop
    copying Lib\ldap\extop\__init__.py -> build\lib.win-amd64-3.6\ldap\extop
    creating build\lib.win-amd64-3.6\ldap\schema
    copying Lib\ldap\schema\models.py -> build\lib.win-amd64-3.6\ldap\schema
    copying Lib\ldap\schema\subentry.py -> build\lib.win-amd64-3.6\ldap\schema
    copying Lib\ldap\schema\tokenizer.py -> build\lib.win-amd64-3.6\ldap\schema
    copying Lib\ldap\schema\__init__.py -> build\lib.win-amd64-3.6\ldap\schema
    creating build\lib.win-amd64-3.6\slapdtest
    copying Lib\slapdtest\_slapdtest.py -> build\lib.win-amd64-3.6\slapdtest
    copying Lib\slapdtest\__init__.py -> build\lib.win-amd64-3.6\slapdtest
    running egg_info
    writing Lib\python_ldap.egg-info\PKG-INFO
    writing dependency_links to Lib\python_ldap.egg-info\dependency_links.txt
    writing requirements to Lib\python_ldap.egg-info\requires.txt
    writing top-level names to Lib\python_ldap.egg-info\top_level.txt
    reading manifest file 'Lib\python_ldap.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'Doc\.build'
    writing manifest file 'Lib\python_ldap.egg-info\SOURCES.txt'
    creating build\lib.win-amd64-3.6\slapdtest\certs
    copying Lib\slapdtest\certs\README -> build\lib.win-amd64-3.6\slapdtest\certs
    copying Lib\slapdtest\certs\ca.conf -> build\lib.win-amd64-3.6\slapdtest\certs
    copying Lib\slapdtest\certs\ca.pem -> build\lib.win-amd64-3.6\slapdtest\certs
    copying Lib\slapdtest\certs\client.conf -> build\lib.win-amd64-3.6\slapdtest\certs
    copying Lib\slapdtest\certs\client.key -> build\lib.win-amd64-3.6\slapdtest\certs
    copying Lib\slapdtest\certs\client.pem -> build\lib.win-amd64-3.6\slapdtest\certs
    copying Lib\slapdtest\certs\gencerts.sh -> build\lib.win-amd64-3.6\slapdtest\certs
    copying Lib\slapdtest\certs\gennssdb.sh -> build\lib.win-amd64-3.6\slapdtest\certs
    copying Lib\slapdtest\certs\server.conf -> build\lib.win-amd64-3.6\slapdtest\certs
    copying Lib\slapdtest\certs\server.key -> build\lib.win-amd64-3.6\slapdtest\certs
    copying Lib\slapdtest\certs\server.pem -> build\lib.win-amd64-3.6\slapdtest\certs
    running build_ext
    building '_ldap' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\Modules
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.2.0 "-DLDAPMODULE_AUTHOR=python-ldap project" "-DLDAPMODULE_LICENSE=Python style" -IModules -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -IC:\Sybase\OCS-15_0\include -IC:\bvsistemas\servers\IBM\MQ\tools\c\include -IC:\bvsistemas\servers\IBM\MQ\tools\cplus\include /TcModules/LDAPObject.c /Fobuild\temp.win-amd64-3.6\Release\Modules/LDAPObject.obj
    LDAPObject.c
    c:\users\andre.raucci\appdata\local\temp\pip-install-88240aor\python-ldap\modules\constants.h(7): fatal error C1083: Cannot open include file: 'lber.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\projetos\python\scraping\env_erick36\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ANDRE~1.RAU\\AppData\\Local\\Temp\\pip-install-88240aor\\python-ldap\\setup.py'"'"'; __file__='"'"'C:\\Users\\ANDRE~1.RAU\\AppData\\Local\\Temp\\pip-install-88240aor\\python-ldap\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ANDRE~1.RAU\AppData\Local\Temp\pip-record-zkakm9rc\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\projetos\python\scraping\env_erick36\include\site\python3.6\python-ldap' Check the logs for full command output.

**Comment by raucci2000** [comment]
Thomas, to simulate similar envrionment, you just need the following things:
 - Winddddows 10 (x64)
 - Python 3.6.4 (x64)
Thank you!

**Comment by drowolath** [comment]
Hello @raucci2000 ,
I was able to reproduce the bug even on my Debian machine (I think I was missing something yesterday).
Anyway, it is related to pyldap, its deprecation and the fact that installing python-ldap requires some [build prerequisites](https://python-ldap.org/en/python-ldap-3.2.0/installing.html#build-prerequisites).

I'll first have to explicitly change the dependencies in the package, test and roll out a release with installation guidelines.

**Comment by raucci2000** [comment]
Hello @drowolath ,
Firstly, thank you very much for your help and feedback. Do you have any provision when that it will be fixed?

Thanks!

**Comment by drowolath** [comment]
Hello @raucci2000,
sorry for the really long delay in replying.
I had some personal issues to deal with and I couldn't take care of this issue.
Do you have libsasl2-dev and libldap2-dev installed? Installing them should provide the missing headers for pyldap to be correctly installed.
Can you please try that? I'll close the issue for now, please feel free to re-open it if it does not work.

Again, so sorry.
