### ISSUE TITLE
Token time duration

### ISSUE THREAD

**Issue by cvidal25** [drowolath/flask-ldap-auth#4]
Hi, is it possible to change the duration of the token?

**Comment by drowolath** [comment]
Hi @cvidal25 ,
after thinking about it, I guess it makes sense for anyone to have control over this parameter.
To implement this, I'm thinking of a modification of the `login_required` decorator: have it accept parameters, token's duration would be one of them, and call it like this in your API:

```
@app.route('/')
@login_required(token_duration=3600)
def hello():
    return 'Hello, world'
```

Does this look like something that could be helpful?
Could you please submit a PR for this? :)

**Comment by drowolath** [comment]
Solved by commit https://github.com/drowolath/flask-ldap-auth/commit/0d88ca7f8994d029437b2662bd84b0b59fbccfeb : call `/request-token` endpoint with parameter `token_duration=3600`
