### ISSUE TITLE
ldap.NO_SUCH_OBJECT with login protected ldap

### ISSUE THREAD

**Issue by oliv3340** [drowolath/flask-ldap-auth#5]
Hi, I'm pretty new in flask and I try to build my first API using an LDAP as an authentication mecanisme. And I'm currently stuck with this ldap.NO_SUCH_OBJECT issue even with your demo code (hello world). It's seems that python currently bind the LDAP which is protected with credentials.

Here's my env 
* Python 3.8.2
* OPENLDAP

you can deploy the exact same LDAP env with this compose file
`  
  version: '3'
  services:

    ldap:
      container_name: ldap
      image: osixia/openldap:latest
      ports:
        - 389:389
      environment:
        - LDAP_ORGANISATION=com
        - LDAP_DOMAIN=my-domain.com
        - LDAP_ADMIN_PASSWORD=admin
        - LDAP_CONFIG_PASSWORD=admin
        - LDAP_READONLY_USER=true
        - LDAP_READONLY_USER_USERNAME=ldap-ro
        - LDAP_READONLY_USER_PASSWORD=readonly
  
    lam:
      container_name: lam
      image: ldapaccountmanager/lam:stable
      ports:
        - 8888:80
`
Then I use LAM to create a random user.

I've setup my API with this config:
LDAP_AUTH_SERVER = 'ldap://127.0.0.1:389'
LDAP_TOP_DN = 'dc=my-domain,dc=com'
LDAP_USERNAME = 'cn=ldap-ro,dc=my-domain,dc=com'
LDAP_PASSWORD = 'readonly'

And I try to auth with the endpoint using `?authenticated_search=true` but I've still got this issue.

Thanks for your help.

**Comment by drowolath** [comment]
Hello @oliv3340 ,
so sorry for replying two-days late.
Could you please show me how you're trying to authenticate?
The goal of flask-ldap-auth is to provide you a simple, yet practical way, to protect your Flask API endpoints with existing LDAP credentials. To do so, it actually let you generate tokens using said credentials.

Again sorry for my delay in replying.

**Comment by oliv3340** [comment]
Hi,

You mean how I make my request ? I've just follow your README for now so I just query the API with basic auth with curl like this :
`$ curl -X POST -u ldap-ro http://127.0.0.1/auth/request-token?authenticated_search=true`

I've tried an other user created on my ldap server but same output.

Don't worry for the delay, it's just a personnal project.
Thanks.

**Comment by drowolath** [comment]
Hello @oliv3340 ,

regarding your issue, it appears that python-ldap library changed the signature of the LDAPObject.bind_s function, enforcing the use of the full DN.

Also, since you are performing an authenticated_search, you must provide the search_criteria of the entity you are using. In your example this would be ` cn`  .
Therefore, your request will look like this:
```
$ curl -X POST -u ldap-ro http://127.0.0.1/auth/request-token?authenticated_search=true&search_criteria=cn
```

I updated my code and it should be working now with version 0.2.4

Let me know if this works for you.

**Comment by drowolath** [comment]
I'll be closing this issue for now.
Feel free to re-open it if the previous commit didn't fix it.
